connectors:
-
  connector_id: ""
  service_type: "azure_blob_storage"

elasticsearch:
  host: "http://host.docker.internal:9200"
  api_key: ${AZCONFIG_APIKEY}
  log_level: INFO
  request_timeout: 120
  max_wait_duration: 60
# Run this command
# docker run --env-file "D:\DSPM\elastic-start-local\.env" -v "D:\DSPM\elastic-start-local\elastic-connectors:/azconfig" --tty --rm docker.elastic.co/integrations/elastic-connectors:8.17.1 /app/bin/elastic-ingest -c /azconfig/azconfig.yml