connectors:
-
  connector_id: ${AZCONFIG_CONNECTOR_ID}
  service_type: "azure_blob_storage"
  configuration:
    account_name: ${AZCONFIG_ACCOUNTNAME}
    account_key: ${AZCONFIG_ACCOUNTKEY}
    blob_endpoint: ${AZCONFIG_BLOBENDPOINT}
    containers: ${AZCONFIG_CONTAINERS}
    use_text_extraction_service: true
    
elasticsearch:
  host: "http://host.docker.internal:9200"
  api_key: ${AZCONFIG_APIKEY}
  log_level: INFO
  request_timeout: 120
  max_wait_duration: 60
