connectors:
-
  connector_id: ${S3CONFIG_CONNECTOR_ID}
  service_type: "s3"
  configuration:
    bucket: ${buckets}
    access_key_id: ${aws_access_key_id}
    secret_access_key: ${aws_secret_access_key}
    use_text_extraction_service: true

elasticsearch:
  host: "http://host.docker.internal:9200"
  api_key: ${S3CONFIG_APIKEY}
  log_level: INFO
  request_timeout: 120
  max_wait_duration: 60