FROM node:22.21.1-alpine3.23@sha256:0340fa682d72068edf603c305bfbc10e23219fb0e40df58d9ea4d6f33a9798bf
WORKDIR /app

COPY package*.json ./
RUN npm install
COPY . .

RUN apk add --no-cache powershell

EXPOSE 4000

USER node

CMD ["npm", "start"]